---
production:    
  aws_region: "eu-central-1"
  profile_name: "default"
  project_name: "pigeon-pictures"
  runtime: "python3.8"
  s3_bucket: "pigeon.pictures"
  api_gateway_enabled: false
  exclude: ["private.template.py", "README.md"]
  keep_warm: false
  lambda_description: "pigeon.pictures image URL fetcher and static page creator"
  timeout_seconds: 60
  memory_size: 128
  events:
  - function: "pigeonpictures.lambda.main"
    expression: "cron(0/30 * * * ? *)"
